### ISSUE TITLE
quoted-string の扱いがRFC5322と異なる？

### ISSUE THREAD

**Issue by take-ookubo** [esminc/kawaii_email_address#11]
初めまして、take-ookubo と申します。
普段から大変便利なライブラリなどを、使用させていただき誠にありがとうございます。

さて本題なのですが、件名にある通り、
quoted-string は、色々な参考文献をあたると、
ローカルパート全体を囲む仕様となっているようなのですが、
実装では `abc"defghi"xyz@example.com` が valid となります。
これをRFC5322 に沿ったバリデータに修正頂くことはできますでしょうか？

quoted-string は 解釈が非常にややこしいので、
そこまで厳密に実装してないという事でしたら、大変申し訳ありません。

参考文献:
http://en.wikipedia.org/wiki/Email_address
http://orgachem.hatenablog.com/entry/2013/11/26/015343

**Comment by takiy33** [comment]
I will close this because #12 is merged.
