### ISSUE TITLE
Would you please release new version?

### ISSUE THREAD

**Issue by takiy33** [esminc/kawaii_email_address#14]
@moro Would you please release new version if you have the time?

**Comment by hanachin** [comment]
diff: [Comparing v0.1.3...master · esminc/kawaii_email_address](https://github.com/esminc/kawaii_email_address/compare/v0.1.3...master)

**Comment by takkanm** [comment]
0.1.4 released on Apr 12.

**Comment by takiy33** [comment]
Thank you
